*"* use this source file for the definition and implementation of
*"* local helper classes, interface definitions and type
*"* declarations
class lcl_repository DEFINITION.

PUBLIC SECTION.

    class-METHODS get_js_barcode_lib
        returning
        value(result) type string.


endclass.

CLASS lcl_repository IMPLEMENTATION.

  METHOD get_js_barcode_lib.

    result = `` && |\n|  &&
`!function(t){var e={};function n(r){if(e[r])return e[r].exports;var o=e[r]={i:r,l:!1,exports:{}};return t[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=t,n.c=e,n.d=function(t,e,r){n.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:r}` &&
`)},n.r=function(t){&quot;undefined&quot;!=typeof Symbol&amp;&amp;Symbol.toStringTag&amp;&amp;Object.defineProperty(t,Symbol.toStringTag,{value:&quot;Module&quot;}),Object.defineProperty(t,&quot;__esModule&quot;,{value:!0})},n.t=function(t,e){if(` &&
`1&amp;e&amp;&amp;(t=n(t)),8&amp;e)return t;if(4&amp;e&amp;&amp;&quot;object&quot;==typeof t&amp;&amp;t&amp;&amp;t.__esModule)return t;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,&quot;default&quot;,{enumerable:!0,value:t}),2&amp;` &&
`e&amp;&amp;&quot;string&quot;!=typeof t)for(var o in t)n.d(r,o,function(e){return t[e]}.bind(null,o));return r},n.n=function(t){var e=t&amp;&amp;t.__esModule?function(){return t.default}:function(){return t};return n.d(e,&quot;a&quot;,e),e},n.o=` &&
`function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},n.p=&quot;&quot;,n(n.s=15)}([function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});e.default=function t(e,n){!function(t,e){if(!(t instan` &&
`ceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,t),this.data=e,this.text=n.text||e,this.options=n}},function(t,e,n){&quot;use strict&quot;;var r;function o(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,` &&
`enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var i=e.SET_A=0,a=e.SET_B=1,u=e.SET_C=2,f=(e.SHIFT=98,e.START_A=103),c=e.START_B=104,s=e.START_C=105;e.MODULO=103,e.STOP=106,e.FNC1=2` &&
`07,e.SET_BY_CODE=(o(r={},f,i),o(r,c,a),o(r,s,u),r),e.SWAP={101:i,100:a,99:u},e.A_START_CHAR=String.fromCharCode(208),e.B_START_CHAR=String.fromCharCode(209),e.C_START_CHAR=String.fromCharCode(210),e.A_CHARS=&quot;[\0-_È-Ï]&quot;,e.B_CHARS=&quot;` &&
`[ -È-Ï]&quot;,e.C_CHARS=&quot;(Ï*[0-9]{2}Ï*)&quot;,e.BARS=[11011001100,11001101100,11001100110,10010011e3,10010001100,10001001100,10011001e3,10011000100,10001100100,11001001e3,11001000100,11000100100,10110011100,10011011100,10011001110,10111001` &&
`100,10011101100,10011100110,11001110010,11001011100,11001001110,11011100100,11001110100,11101101110,11101001100,11100101100,11100100110,11101100100,11100110100,11100110010,11011011e3,11011000110,11000110110,10100011e3,10001011e3,10001000110,1011` &&
`0001e3,10001101e3,10001100010,11010001e3,11000101e3,11000100010,10110111e3,10110001110,10001101110,10111011e3,10111000110,10001110110,11101110110,11010001110,11000101110,11011101e3,11011100010,11011101110,11101011e3,11101000110,11100010110,11101` &&
`101e3,11101100010,11100011010,11101111010,11001000010,11110001010,1010011e4,10100001100,1001011e4,10010000110,10000101100,10000100110,1011001e4,10110000100,1001101e4,10011000010,10000110100,10000110010,11000010010,1100101e4,11110111010,110000101` &&
`00,10001111010,10100111100,10010111100,10010011110,10111100100,10011110100,10011110010,11110100100,11110010100,11110010010,11011011110,11011110110,11110110110,10101111e3,10100011110,10001011110,10111101e3,10111100010,11110101e3,11110100010,10111` &&
`011110,10111101110,11101011110,11110101110,11010000100,1101001e4,11010011100,1100011101011]},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});e.SIDE_BIN=&quot;101&quot;,e.MIDDLE_BIN=&quot;01010&qu` &&
`ot;,e.BINARIES={L:[&quot;0001101&quot;,&quot;0011001&quot;,&quot;0010011&quot;,&quot;0111101&quot;,&quot;0100011&quot;,&quot;0110001&quot;,&quot;0101111&quot;,&quot;0111011&quot;,&quot;0110111&quot;,&quot;0001011&quot;],G:[&quot;0100111&quot;,&q` &&
`uot;0110011&quot;,&quot;0011011&quot;,&quot;0100001&quot;,&quot;0011101&quot;,&quot;0111001&quot;,&quot;0000101&quot;,&quot;0010001&quot;,&quot;0001001&quot;,&quot;0010111&quot;],R:[&quot;1110010&quot;,&quot;1100110&quot;,&quot;1101100&quot;,&qu` &&
`ot;1000010&quot;,&quot;1011100&quot;,&quot;1001110&quot;,&quot;1010000&quot;,&quot;1000100&quot;,&quot;1001000&quot;,&quot;1110100&quot;],O:[&quot;0001101&quot;,&quot;0011001&quot;,&quot;0010011&quot;,&quot;0111101&quot;,&quot;0100011&quot;,&quo` &&
`t;0110001&quot;,&quot;0101111&quot;,&quot;0111011&quot;,&quot;0110111&quot;,&quot;0001011&quot;],E:[&quot;0100111&quot;,&quot;0110011&quot;,&quot;0011011&quot;,&quot;0100001&quot;,&quot;0011101&quot;,&quot;0111001&quot;,&quot;0000101&quot;,&quot` &&
`;0010001&quot;,&quot;0001001&quot;,&quot;0010111&quot;]},e.EAN2_STRUCTURE=[&quot;LL&quot;,&quot;LG&quot;,&quot;GL&quot;,&quot;GG&quot;],e.EAN5_STRUCTURE=[&quot;GGLLL&quot;,&quot;GLGLL&quot;,&quot;GLLGL&quot;,&quot;GLLLG&quot;,&quot;LGGLL&quot;,&` &&
`quot;LLGGL&quot;,&quot;LLLGG&quot;,&quot;LGLGL&quot;,&quot;LGLLG&quot;,&quot;LLGLG&quot;],e.EAN13_STRUCTURE=[&quot;LLLLLL&quot;,&quot;LLGLGG&quot;,&quot;LLGGLG&quot;,&quot;LLGGGL&quot;,&quot;LGLLGG&quot;,&quot;LGGLLG&quot;,&quot;LGGGLL&quot;,&qu` &&
`ot;LGLGLG&quot;,&quot;LGLGGL&quot;,&quot;LGGLGL&quot;]},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r=n(2);e.default=function(t,e,n){var o=t.split(&quot;&quot;).map((function(t,n){return ` &&
`r.BINARIES[e[n]]})).map((function(e,n){return e?e[t[n]]:&quot;&quot;}));if(n){var i=t.length-1;o=o.map((function(t,e){return e&lt;i?t+n:t}))}return o.join(&quot;&quot;)}},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esM` &&
`odule&quot;,{value:!0});var r,o=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function` &&
`(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),i=n(0);var a=function(t){function e(t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),function(t,e){if(!t` &&
`)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,t` &&
`,n))}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value` &&
`:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),o(e,[{key:&quot;encode&quot;,value:function(){for(var t=&quot;110&quot;,e=0;e&lt;this.data.length;e++){var n=parseI` &&
`nt(this.data[e]).toString(2);n=u(n,4-n.length);for(var r=0;r&lt;n.length;r++)t+=&quot;0&quot;==n[r]?&quot;100&quot;:&quot;110&quot;}return{data:t+=&quot;1001&quot;,text:this.text}}},{key:&quot;valid&quot;,value:function(){return-1!==this.data.se` &&
`arch(/^[0-9]+$/)}}]),e}(((r=i)&amp;&amp;r.__esModule?r:{default:r}).default);function u(t,e){for(var n=0;n&lt;e;n++)t=&quot;0&quot;+t;return t}e.default=a},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{va` &&
`lue:!0});var r,o=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return ` &&
`n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),i=n(0),a=(r=i)&amp;&amp;r.__esModule?r:{default:r},u=n(1);var f=function(t){function e(t,n){!function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;` &&
`)}(this,e);var r=function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__proto__||O` &&
`bject.getPrototypeOf(e)).call(this,t.substring(1),n));return r.bytes=t.split(&quot;&quot;).map((function(t){return t.charCodeAt(0)})),r}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expr` &&
`ession must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__p` &&
`roto__=e)}(e,t),o(e,[{key:&quot;valid&quot;,value:function(){return/^[\x00-\x7F\xC8-\xD3]+$/.test(this.data)}},{key:&quot;encode&quot;,value:function(){var t=this.bytes,n=t.shift()-105,r=u.SET_BY_CODE[n];if(void 0===r)throw new RangeError(&quot;` &&
`The encoding does not start with a start character.&quot;);!0===this.shouldEncodeAsEan128()&amp;&amp;t.unshift(u.FNC1);var o=e.next(t,1,r);return{text:this.text===this.data?this.text.replace(/[^\x20-\x7E]/g,&quot;&quot;):this.text,data:e.getBar(` &&
`n)+o.result+e.getBar((o.checksum+n)%u.MODULO)+e.getBar(u.STOP)}}},{key:&quot;shouldEncodeAsEan128&quot;,value:function(){var t=this.options.ean128||!1;return&quot;string&quot;==typeof t&amp;&amp;(t=&quot;true&quot;===t.toLowerCase()),t}}],[{key:` &&
`&quot;getBar&quot;,value:function(t){return u.BARS[t]?u.BARS[t].toString():&quot;&quot;}},{key:&quot;correctIndex&quot;,value:function(t,e){if(e===u.SET_A){var n=t.shift();return n&lt;32?n+64:n-32}return e===u.SET_B?t.shift()-32:10*(t.shift()-48` &&
`)+t.shift()-48}},{key:&quot;next&quot;,value:function(t,n,r){if(!t.length)return{result:&quot;&quot;,checksum:0};var o=void 0,i=void 0;if(t[0]&gt;=200){i=t.shift()-105;var a=u.SWAP[i];void 0!==a?o=e.next(t,n+1,a):(r!==u.SET_A&amp;&amp;r!==u.SET_` &&
`B||i!==u.SHIFT||(t[0]=r===u.SET_A?t[0]&gt;95?t[0]-96:t[0]:t[0]&lt;32?t[0]+96:t[0]),o=e.next(t,n+1,r))}else i=e.correctIndex(t,r),o=e.next(t,n+1,r);var f=i*n;return{result:e.getBar(i)+o.result,checksum:f+o.checksum}}}]),e}(a.default);e.default=f}` &&
`,function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0}),e.mod10=function(t){for(var e=0,n=0;n&lt;t.length;n++){var r=parseInt(t[n]);(n+t.length)%2==0?e+=r:e+=2*r%10+Math.floor(2*r/10)}return(10-e%10)%10` &&
`},e.mod11=function(t){for(var e=0,n=[2,3,4,5,6,7],r=0;r&lt;t.length;r++){var o=parseInt(t[t.length-1-r]);e+=n[r%n.length]*o}return(11-e%11)%11}},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});va` &&
`r r=Object.assign||function(t){for(var e=1;e&lt;arguments.length;e++){var n=arguments[e];for(var r in n)Object.prototype.hasOwnProperty.call(n,r)&amp;&amp;(t[r]=n[r])}return t};e.default=function(t,e){return r({},t,e)}},function(t,e,n){&quot;use` &&
` strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Ob` &&
`ject.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),o=n(2),i=a(n(3));function a(t){return t&amp;&amp;t.__esModule?t:{default:t}}var u=function(t){function e(t,n){!function(t,e){if(!(t` &&
` instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e);var r=function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&q` &&
`uot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,t,n));return r.fontSize=!n.flat&amp;&amp;n.fontSize&gt;10*n.width?10*n.width:n.fontSize,r.guardHeight=n.height+r.fontSize/2+n.text` &&
`Margin,r}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{v` &&
`alue:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),r(e,[{key:&quot;encode&quot;,value:function(){return this.options.flat?this.encodeFlat():this.encodeGuarded()}}` &&
`,{key:&quot;leftText&quot;,value:function(t,e){return this.text.substr(t,e)}},{key:&quot;leftEncode&quot;,value:function(t,e){return(0,i.default)(t,e)}},{key:&quot;rightText&quot;,value:function(t,e){return this.text.substr(t,e)}},{key:&quot;rig` &&
`htEncode&quot;,value:function(t,e){return(0,i.default)(t,e)}},{key:&quot;encodeGuarded&quot;,value:function(){var t={fontSize:this.fontSize},e={height:this.guardHeight};return[{data:o.SIDE_BIN,options:e},{data:this.leftEncode(),text:this.leftTex` &&
`t(),options:t},{data:o.MIDDLE_BIN,options:e},{data:this.rightEncode(),text:this.rightText(),options:t},{data:o.SIDE_BIN,options:e}]}},{key:&quot;encodeFlat&quot;,value:function(){return{data:[o.SIDE_BIN,this.leftEncode(),o.MIDDLE_BIN,this.rightE` &&
`ncode(),o.SIDE_BIN].join(&quot;&quot;),text:this.text}}}]),e}(a(n(0)).default);e.default=u},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r=function(){function t(t,e){for(var n=0;n&lt;e.len` &&
`gth;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}();e.checksum=u;v` &&
`ar o=i(n(3));function i(t){return t&amp;&amp;t.__esModule?t:{default:t}}var a=function(t){function e(t,n){!function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),-1!==t.search(/^[0-9]{11}$/` &&
`)&amp;&amp;(t+=u(t));var r=function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__` &&
`proto__||Object.getPrototypeOf(e)).call(this,t,n));return r.displayValue=n.displayValue,n.fontSize&gt;10*n.width?r.fontSize=10*n.width:r.fontSize=n.fontSize,r.guardHeight=n.height+r.fontSize/2+n.textMargin,r}return function(t,e){if(&quot;functio` &&
`n&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:` &&
`!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),r(e,[{key:&quot;valid&quot;,value:function(){return-1!==this.data.search(/^[0-9]{12}$/)&amp;&amp;this.data[11]==u(this.data)}},{key:&quot;encode&quot;,value:` &&
`function(){return this.options.flat?this.flatEncoding():this.guardedEncoding()}},{key:&quot;flatEncoding&quot;,value:function(){var t=&quot;&quot;;return t+=&quot;101&quot;,t+=(0,o.default)(this.data.substr(0,6),&quot;LLLLLL&quot;),t+=&quot;0101` &&
`0&quot;,t+=(0,o.default)(this.data.substr(6,6),&quot;RRRRRR&quot;),{data:t+=&quot;101&quot;,text:this.text}}},{key:&quot;guardedEncoding&quot;,value:function(){var t=[];return this.displayValue&amp;&amp;t.push({data:&quot;00000000&quot;,text:thi` &&
`s.text.substr(0,1),options:{textAlign:&quot;left&quot;,fontSize:this.fontSize}}),t.push({data:&quot;101&quot;+(0,o.default)(this.data[0],&quot;L&quot;),options:{height:this.guardHeight}}),t.push({data:(0,o.default)(this.data.substr(1,5),&quot;LL` &&
`LLL&quot;),text:this.text.substr(1,5),options:{fontSize:this.fontSize}}),t.push({data:&quot;01010&quot;,options:{height:this.guardHeight}}),t.push({data:(0,o.default)(this.data.substr(6,5),&quot;RRRRR&quot;),text:this.text.substr(6,5),options:{f` &&
`ontSize:this.fontSize}}),t.push({data:(0,o.default)(this.data[11],&quot;R&quot;)+&quot;101&quot;,options:{height:this.guardHeight}}),this.displayValue&amp;&amp;t.push({data:&quot;00000000&quot;,text:this.text.substr(11,1),options:{textAlign:&quo` &&
`t;right&quot;,fontSize:this.fontSize}}),t}}]),e}(i(n(0)).default);function u(t){var e,n=0;for(e=1;e&lt;11;e+=2)n+=parseInt(t[e]);for(e=0;e&lt;11;e+=2)n+=3*parseInt(t[e]);return(10-n%10)%10}e.default=a},function(t,e,n){&quot;use strict&quot;;Obje` &&
`ct.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r,o=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.definePrope` &&
`rty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),i=n(31),a=n(0);function u(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}function f(t,e){if(!t)throw ` &&
`new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}var c=function(t){function e(){return u(this,e),f(this,(e.__prot` &&
`o__||Object.getPrototypeOf(e)).apply(this,arguments))}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.` &&
`create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),o(e,[{key:&quot;valid&quot;,value:function(){return-1!==this.data.` &&
`search(/^([0-9]{2})+$/)}},{key:&quot;encode&quot;,value:function(){var t=this,e=this.data.match(/.{2}/g).map((function(e){return t.encodePair(e)})).join(&quot;&quot;);return{data:i.START_BIN+e+i.END_BIN,text:this.text}}},{key:&quot;encodePair&qu` &&
`ot;,value:function(t){var e=i.BINARIES[t[1]];return i.BINARIES[t[0]].split(&quot;&quot;).map((function(t,n){return(&quot;1&quot;===t?&quot;111&quot;:&quot;1&quot;)+(&quot;1&quot;===e[n]?&quot;000&quot;:&quot;0&quot;)})).join(&quot;&quot;)}}]),e}` &&
`(((r=a)&amp;&amp;r.__esModule?r:{default:r}).default);e.default=c},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0}),e.default=function(t){var e=[&quot;width&quot;,&quot;height&quot;,&quot;textMarg` &&
`in&quot;,&quot;fontSize&quot;,&quot;margin&quot;,&quot;marginTop&quot;,&quot;marginBottom&quot;,&quot;marginLeft&quot;,&quot;marginRight&quot;];for(var n in e)e.hasOwnProperty(n)&amp;&amp;(n=e[n],&quot;string&quot;==typeof t[n]&amp;&amp;(t[n]=pa` &&
`rseInt(t[n],10)));&quot;string&quot;==typeof t.displayValue&amp;&amp;(t.displayValue=&quot;false&quot;!=t.displayValue);return t}},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r={width:2,h` &&
`eight:100,format:&quot;auto&quot;,displayValue:!0,fontOptions:&quot;&quot;,font:&quot;monospace&quot;,text:void 0,textAlign:&quot;center&quot;,textPosition:&quot;bottom&quot;,textMargin:2,fontSize:20,background:&quot;#ffffff&quot;,lineColor:&quo` &&
`t;#000000&quot;,margin:10,marginTop:void 0,marginBottom:void 0,marginLeft:void 0,marginRight:void 0,valid:function(){}};e.default=r},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0}),e.getTotalWidt` &&
`hOfEncodings=e.calculateEncodingAttributes=e.getBarcodePadding=e.getEncodingHeight=e.getMaximumHeightOfEncodings=void 0;var r,o=n(7),i=(r=o)&amp;&amp;r.__esModule?r:{default:r};function a(t,e){return e.height+(e.displayValue&amp;&amp;t.text.leng` &&
`th&gt;0?e.fontSize+e.textMargin:0)+e.marginTop+e.marginBottom}function u(t,e,n){if(n.displayValue&amp;&amp;e&lt;t){if(&quot;center&quot;==n.textAlign)return Math.floor((t-e)/2);if(&quot;left&quot;==n.textAlign)return 0;if(&quot;right&quot;==n.te` &&
`xtAlign)return Math.floor(t-e)}return 0}function f(t,e,n){var r;if(n)r=n;else{if(&quot;undefined&quot;==typeof document)return 0;r=document.createElement(&quot;canvas&quot;).getContext(&quot;2d&quot;)}r.font=e.fontOptions+&quot; &quot;+e.fontSiz` &&
`e+&quot;px &quot;+e.font;var o=r.measureText(t);return o?o.width:0}e.getMaximumHeightOfEncodings=function(t){for(var e=0,n=0;n&lt;t.length;n++)t[n].height&gt;e&amp;&amp;(e=t[n].height);return e},e.getEncodingHeight=a,e.getBarcodePadding=u,e.calc` &&
`ulateEncodingAttributes=function(t,e,n){for(var r=0;r&lt;t.length;r++){var o,c=t[r],s=(0,i.default)(e,c.options);o=s.displayValue?f(c.text,s,n):0;var l=c.data.length*s.width;c.width=Math.ceil(Math.max(o,l)),c.height=a(c,s),c.barcodePadding=u(o,l` &&
`,s)}},e.getTotalWidthOfEncodings=function(t){for(var e=0,n=0;n&lt;t.length;n++)e+=t[n].width;return e}},function(t,e,n){&quot;use strict&quot;;function r(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;` &&
`)}function o(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}function i(t,e){if(&quot;function&` &&
`quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0` &&
`}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var a=function(t){function e(t,n){r(this,e);var i=o(this,(e.__proto__||Object.getPrototypeOf(e)).call(this` &&
`));return i.name=&quot;InvalidInputException&quot;,i.symbology=t,i.input=n,i.message=&#39;&quot;&#39;+i.input+&#39;&quot; is not a valid input for &#39;+i.symbology,i}return i(e,Error),e}(),u=function(t){function e(){r(this,e);var t=o(this,(e.__` &&
`proto__||Object.getPrototypeOf(e)).call(this));return t.name=&quot;InvalidElementException&quot;,t.message=&quot;Not supported type to render on&quot;,t}return i(e,Error),e}(),f=function(t){function e(){r(this,e);var t=o(this,(e.__proto__||Objec` &&
`t.getPrototypeOf(e)).call(this));return t.name=&quot;NoElementException&quot;,t.message=&quot;No element to render on.&quot;,t}return i(e,Error),e}();e.InvalidInputException=a,e.InvalidElementException=u,e.NoElementException=f},function(t,e,n){&` &&
`quot;use strict&quot;;var r=p(n(16)),o=p(n(7)),i=p(n(41)),a=p(n(42)),u=p(n(43)),f=p(n(11)),c=p(n(49)),s=n(14),l=p(n(12));function p(t){return t&amp;&amp;t.__esModule?t:{default:t}}var d=function(){},h=function(t,e,n){var r=new d;if(void 0===t)th` &&
`row Error(&quot;No element to render on was provided.&quot;);return r._renderProperties=(0,u.default)(t),r._encodings=[],r._options=l.default,r._errorHandler=new c.default(r),void 0!==e&amp;&amp;((n=n||{}).format||(n.format=_()),r.options(n)[n.f` &&
`ormat](e,n).render()),r};for(var y in h.getModule=function(t){return r.default[t]},r.default)r.default.hasOwnProperty(y)&amp;&amp;b(r.default,y);function b(t,e){d.prototype[e]=d.prototype[e.toUpperCase()]=d.prototype[e.toLowerCase()]=function(n,` &&
`r){var i=this;return i._errorHandler.wrapBarcodeCall((function(){r.text=void 0===r.text?void 0:&quot;&quot;+r.text;var a=(0,o.default)(i._options,r);a=(0,f.default)(a);var u=t[e],c=v(n,u,a);return i._encodings.push(c),i}))}}function v(t,e,n){var` &&
` r=new e(t=&quot;&quot;+t,n);if(!r.valid())throw new s.InvalidInputException(r.constructor.name,t);var a=r.encode();a=(0,i.default)(a);for(var u=0;u&lt;a.length;u++)a[u].options=(0,o.default)(n,a[u].options);return a}function _(){return r.defaul` &&
`t.CODE128?&quot;CODE128&quot;:Object.keys(r.default)[0]}function g(t,e,n){e=(0,i.default)(e);for(var r=0;r&lt;e.length;r++)e[r].options=(0,o.default)(n,e[r].options),(0,a.default)(e[r].options);(0,a.default)(n),new(0,t.renderer)(t.element,e,n).r` &&
`ender(),t.afterRender&amp;&amp;t.afterRender()}d.prototype.options=function(t){return this._options=(0,o.default)(this._options,t),this},d.prototype.blank=function(t){var e=new Array(t+1).join(&quot;0&quot;);return this._encodings.push({data:e})` &&
`,this},d.prototype.init=function(){var t;if(this._renderProperties)for(var e in Array.isArray(this._renderProperties)||(this._renderProperties=[this._renderProperties]),this._renderProperties){t=this._renderProperties[e];var n=(0,o.default)(this` &&
`._options,t.options);&quot;auto&quot;==n.format&amp;&amp;(n.format=_()),this._errorHandler.wrapBarcodeCall((function(){var e=v(n.value,r.default[n.format.toUpperCase()],n);g(t,e,n)}))}},d.prototype.render=function(){if(!this._renderProperties)th` &&
`row new s.NoElementException;if(Array.isArray(this._renderProperties))for(var t=0;t&lt;this._renderProperties.length;t++)g(this._renderProperties[t],this._encodings,this._options);else g(this._renderProperties,this._encodings,this._options);retu` &&
`rn this},d.prototype._defaults=l.default,&quot;undefined&quot;!=typeof window&amp;&amp;(window.JsBarcode=h),&quot;undefined&quot;!=typeof jQuery&amp;&amp;(jQuery.fn.JsBarcode=function(t,e){var n=[];return jQuery(this).each((function(){n.push(thi` &&
`s)})),h(n,t,e)}),t.exports=h},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r=n(17),o=n(18),i=n(24),a=n(30),u=n(33),f=n(38),c=n(39),s=n(40);e.default={CODE39:r.CODE39,CODE128:o.CODE128,CODE` &&
`128A:o.CODE128A,CODE128B:o.CODE128B,CODE128C:o.CODE128C,EAN13:i.EAN13,EAN8:i.EAN8,EAN5:i.EAN5,EAN2:i.EAN2,UPC:i.UPC,UPCE:i.UPCE,ITF14:a.ITF14,ITF:a.ITF,MSI:u.MSI,MSI10:u.MSI10,MSI11:u.MSI11,MSI1010:u.MSI1010,MSI1110:u.MSI1110,pharmacode:f.pharma` &&
`code,codabar:c.codabar,GenericBarcode:s.GenericBarcode}},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0}),e.CODE39=void 0;var r,o=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[` &&
`n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),i=n(0);var a=function(t){functi` &&
`on e(t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),t=t.toUpperCase(),n.mod43&amp;&amp;(t+=function(t){return u[t]}(function(t){for(var e=0,n=0;n&lt;t.length;n++)e+=s(t[` &&
`n]);return e%=43}(t))),function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__prot` &&
`o__||Object.getPrototypeOf(e)).call(this,t,n))}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(` &&
`e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),o(e,[{key:&quot;encode&quot;,value:function(){for(var t=c(&quot;*&quot;),` &&
`e=0;e&lt;this.data.length;e++)t+=c(this.data[e])+&quot;0&quot;;return{data:t+=c(&quot;*&quot;),text:this.text}}},{key:&quot;valid&quot;,value:function(){return-1!==this.data.search(/^[0-9A-Z\-\.\ \$\/\+\%]+$/)}}]),e}(((r=i)&amp;&amp;r.__esModule` &&
`?r:{default:r}).default),u=[&quot;0&quot;,&quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,&quot;5&quot;,&quot;6&quot;,&quot;7&quot;,&quot;8&quot;,&quot;9&quot;,&quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;,&quot;E&quot;,&quot;F` &&
`&quot;,&quot;G&quot;,&quot;H&quot;,&quot;I&quot;,&quot;J&quot;,&quot;K&quot;,&quot;L&quot;,&quot;M&quot;,&quot;N&quot;,&quot;O&quot;,&quot;P&quot;,&quot;Q&quot;,&quot;R&quot;,&quot;S&quot;,&quot;T&quot;,&quot;U&quot;,&quot;V&quot;,&quot;W&quot;,` &&
`&quot;X&quot;,&quot;Y&quot;,&quot;Z&quot;,&quot;-&quot;,&quot;.&quot;,&quot; &quot;,&quot;$&quot;,&quot;/&quot;,&quot;+&quot;,&quot;%&quot;,&quot;*&quot;],f=[20957,29783,23639,30485,20951,29813,23669,20855,29789,23645,29975,23831,30533,22295,301` &&
`49,24005,21623,29981,23837,22301,30023,23879,30545,22343,30161,24017,21959,30065,23921,22385,29015,18263,29141,17879,29045,18293,17783,29021,18269,17477,17489,17681,20753,35770];function c(t){return function(t){return f[t].toString(2)}(s(t))}fun` &&
`ction s(t){return u.indexOf(t)}e.CODE39=a},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0}),e.CODE128C=e.CODE128B=e.CODE128A=e.CODE128=void 0;var r=u(n(19)),o=u(n(21)),i=u(n(22)),a=u(n(23));functi` &&
`on u(t){return t&amp;&amp;t.__esModule?t:{default:t}}e.CODE128=r.default,e.CODE128A=o.default,e.CODE128B=i.default,e.CODE128C=a.default},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r=i(n(` &&
`5)),o=i(n(20));function i(t){return t&amp;&amp;t.__esModule?t:{default:t}}function a(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&a` &&
`mp;&quot;function&quot;!=typeof e?t:e}var u=function(t){function e(t,n){if(function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),/^[\x00-\x7F\xC8-\xD3]+$/.test(t))var r=a(this,(e.__proto__` &&
`||Object.getPrototypeOf(e)).call(this,(0,o.default)(t),n));else r=a(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,t,n));return a(r)}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super` &&
` expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):` &&
`t.__proto__=e)}(e,t),e}(r.default);e.default=u},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r=n(1),o=function(t){return t.match(new RegExp(&quot;^&quot;+r.A_CHARS+&quot;*&quot;))[0].lengt` &&
`h},i=function(t){return t.match(new RegExp(&quot;^&quot;+r.B_CHARS+&quot;*&quot;))[0].length},a=function(t){return t.match(new RegExp(&quot;^&quot;+r.C_CHARS+&quot;*&quot;))[0]};function u(t,e){var n=e?r.A_CHARS:r.B_CHARS,o=t.match(new RegExp(&q` &&
`uot;^(&quot;+n+&quot;+?)(([0-9]{2}){2,})([^0-9]|$)&quot;));if(o)return o[1]+String.fromCharCode(204)+f(t.substring(o[1].length));var i=t.match(new RegExp(&quot;^&quot;+n+&quot;+&quot;))[0];return i.length===t.length?t:i+String.fromCharCode(e?205` &&
`:206)+u(t.substring(i.length),!e)}function f(t){var e=a(t),n=e.length;if(n===t.length)return t;t=t.substring(n);var r=o(t)&gt;=i(t);return e+String.fromCharCode(r?206:205)+u(t,r)}e.default=function(t){var e=void 0;if(a(t).length&gt;=2)e=r.C_STAR` &&
`T_CHAR+f(t);else{var n=o(t)&gt;i(t);e=(n?r.A_START_CHAR:r.B_START_CHAR)+u(t,n)}return e.replace(/[\xCD\xCE]([^])[\xCD\xCE]/,(function(t,e){return String.fromCharCode(203)+e}))}},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quo` &&
`t;__esModule&quot;,{value:!0});var r,o=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return f` &&
`unction(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),i=n(5),a=(r=i)&amp;&amp;r.__esModule?r:{default:r},u=n(1);var f=function(t){function e(t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call` &&
` a class as a function&quot;)}(this,e),function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e` &&
`}(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,u.A_START_CHAR+t,n))}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeo` &&
`f e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),o(e,[{key:&quot;valid&quot;,value:function` &&
`(){return new RegExp(&quot;^&quot;+u.A_CHARS+&quot;+$&quot;).test(this.data)}}]),e}(a.default);e.default=f},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r,o=function(){function t(t,e){for(` &&
`var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}` &&
`}(),i=n(5),a=(r=i)&amp;&amp;r.__esModule?r:{default:r},u=n(1);var f=function(t){function e(t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),function(t,e){if(!t)throw new R` &&
`eferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,u.B_START_CHA` &&
`R+t,n))}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{va` &&
`lue:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),o(e,[{key:&quot;valid&quot;,value:function(){return new RegExp(&quot;^&quot;+u.B_CHARS+&quot;+$&quot;).test(this` &&
`.data)}}]),e}(a.default);e.default=f},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r,o=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.` &&
`configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),i=n(5),a=(r=i)&amp;&amp;r.__esModule?r:{default:r},u=n(1);var f=fu` &&
`nction(t){function e(t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#3` &&
`9;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,u.C_START_CHAR+t,n))}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&am` &&
`p;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.` &&
`setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),o(e,[{key:&quot;valid&quot;,value:function(){return new RegExp(&quot;^&quot;+u.C_CHARS+&quot;+$&quot;).test(this.data)}}]),e}(a.default);e.default=f},function(t,e,n){&quot;use strict` &&
`&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0}),e.UPCE=e.UPC=e.EAN2=e.EAN5=e.EAN8=e.EAN13=void 0;var r=c(n(25)),o=c(n(26)),i=c(n(27)),a=c(n(28)),u=c(n(9)),f=c(n(29));function c(t){return t&amp;&amp;t.__esModule?t:{default:t}}e.` &&
`EAN13=r.default,e.EAN8=o.default,e.EAN5=i.default,e.EAN2=a.default,e.UPC=u.default,e.UPCE=f.default},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r,o=function(){function t(t,e){for(var n=0` &&
`;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),i=f` &&
`unction t(e,n,r){null===e&amp;&amp;(e=Function.prototype);var o=Object.getOwnPropertyDescriptor(e,n);if(void 0===o){var i=Object.getPrototypeOf(e);return null===i?void 0:t(i,n,r)}if(&quot;value&quot;in o)return o.value;var a=o.get;return void 0!` &&
`==a?a.call(r):void 0},a=n(2),u=n(8),f=(r=u)&amp;&amp;r.__esModule?r:{default:r};var c=function(t){return(10-t.substr(0,12).split(&quot;&quot;).map((function(t){return+t})).reduce((function(t,e,n){return n%2?t+3*e:t+e}),0)%10)%10},s=function(t){f` &&
`unction e(t,n){!function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),-1!==t.search(/^[0-9]{12}$/)&amp;&amp;(t+=c(t));var r=function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39` &&
`;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,t,n));return r.lastChar=n.lastChar,r}return fu` &&
`nction(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:` &&
`!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),o(e,[{key:&quot;valid&quot;,value:function(){return-1!==this.data.search(/^[0-9]{13}$/)&amp;&amp;+this.data[12]===c(this.data)}},` &&
`{key:&quot;leftText&quot;,value:function(){return i(e.prototype.__proto__||Object.getPrototypeOf(e.prototype),&quot;leftText&quot;,this).call(this,1,6)}},{key:&quot;leftEncode&quot;,value:function(){var t=this.data.substr(1,6),n=a.EAN13_STRUCTUR` &&
`E[this.data[0]];return i(e.prototype.__proto__||Object.getPrototypeOf(e.prototype),&quot;leftEncode&quot;,this).call(this,t,n)}},{key:&quot;rightText&quot;,value:function(){return i(e.prototype.__proto__||Object.getPrototypeOf(e.prototype),&quot` &&
`;rightText&quot;,this).call(this,7,6)}},{key:&quot;rightEncode&quot;,value:function(){var t=this.data.substr(7,6);return i(e.prototype.__proto__||Object.getPrototypeOf(e.prototype),&quot;rightEncode&quot;,this).call(this,t,&quot;RRRRRR&quot;)}},` &&
`{key:&quot;encodeGuarded&quot;,value:function(){var t=i(e.prototype.__proto__||Object.getPrototypeOf(e.prototype),&quot;encodeGuarded&quot;,this).call(this);return this.options.displayValue&amp;&amp;(t.unshift({data:&quot;000000000000&quot;,text` &&
`:this.text.substr(0,1),options:{textAlign:&quot;left&quot;,fontSize:this.fontSize}}),this.options.lastChar&amp;&amp;(t.push({data:&quot;00&quot;}),t.push({data:&quot;00000&quot;,text:this.options.lastChar,options:{fontSize:this.fontSize}}))),t}}` &&
`]),e}(f.default);e.default=s},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r,o=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configur` &&
`able=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),i=function t(e,n,r){null===e&amp;&amp;(e=Function.prototype);var o=Object.` &&
`getOwnPropertyDescriptor(e,n);if(void 0===o){var i=Object.getPrototypeOf(e);return null===i?void 0:t(i,n,r)}if(&quot;value&quot;in o)return o.value;var a=o.get;return void 0!==a?a.call(r):void 0},a=n(8),u=(r=a)&amp;&amp;r.__esModule?r:{default:r` &&
`};var f=function(t){return(10-t.substr(0,7).split(&quot;&quot;).map((function(t){return+t})).reduce((function(t,e,n){return n%2?t+e:t+3*e}),0)%10)%10},c=function(t){function e(t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&q` &&
`uot;Cannot call a class as a function&quot;)}(this,e),-1!==t.search(/^[0-9]{7}$/)&amp;&amp;(t+=f(t)),function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;obje` &&
`ct&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,t,n))}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must` &&
` either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(` &&
`e,t),o(e,[{key:&quot;valid&quot;,value:function(){return-1!==this.data.search(/^[0-9]{8}$/)&amp;&amp;+this.data[7]===f(this.data)}},{key:&quot;leftText&quot;,value:function(){return i(e.prototype.__proto__||Object.getPrototypeOf(e.prototype),&qu` &&
`ot;leftText&quot;,this).call(this,0,4)}},{key:&quot;leftEncode&quot;,value:function(){var t=this.data.substr(0,4);return i(e.prototype.__proto__||Object.getPrototypeOf(e.prototype),&quot;leftEncode&quot;,this).call(this,t,&quot;LLLL&quot;)}},{ke` &&
`y:&quot;rightText&quot;,value:function(){return i(e.prototype.__proto__||Object.getPrototypeOf(e.prototype),&quot;rightText&quot;,this).call(this,4,4)}},{key:&quot;rightEncode&quot;,value:function(){var t=this.data.substr(4,4);return i(e.prototy` &&
`pe.__proto__||Object.getPrototypeOf(e.prototype),&quot;rightEncode&quot;,this).call(this,t,&quot;RRRR&quot;)}}]),e}(u.default);e.default=c},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r=f` &&
`unction(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.pro` &&
`totype,n),r&amp;&amp;t(e,r),e}}(),o=n(2),i=u(n(3)),a=u(n(0));function u(t){return t&amp;&amp;t.__esModule?t:{default:t}}var f=function(t){function e(t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as ` &&
`a function&quot;)}(this,e),function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__` &&
`proto__||Object.getPrototypeOf(e)).call(this,t,n))}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.cre` &&
`ate(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),r(e,[{key:&quot;valid&quot;,value:function(){return-1!==this.data.sea` &&
`rch(/^[0-9]{5}$/)}},{key:&quot;encode&quot;,value:function(){var t,e=o.EAN5_STRUCTURE[(t=this.data,t.split(&quot;&quot;).map((function(t){return+t})).reduce((function(t,e,n){return n%2?t+9*e:t+3*e}),0)%10)];return{data:&quot;1011&quot;+(0,i.defa` &&
`ult)(this.data,e,&quot;01&quot;),text:this.text}}}]),e}(a.default);e.default=f},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var` &&
` r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),o=n(2),i=a(n(3));function ` &&
`a(t){return t&amp;&amp;t.__esModule?t:{default:t}}var u=function(t){function e(t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),function(t,e){if(!t)throw new ReferenceErro` &&
`r(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,t,n))}return function(t,e` &&
`){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writabl` &&
`e:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),r(e,[{key:&quot;valid&quot;,value:function(){return-1!==this.data.search(/^[0-9]{2}$/)}},{key:&quot;encode&quot;,value:function(){var t=o.E` &&
`AN2_STRUCTURE[parseInt(this.data)%4];return{data:&quot;1011&quot;+(0,i.default)(this.data,t,&quot;01&quot;),text:this.text}}}]),e}(a(n(0)).default);e.default=u},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot` &&
`;,{value:!0});var r=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){retu` &&
`rn n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),o=u(n(3)),i=u(n(0)),a=n(9);function u(t){return t&amp;&amp;t.__esModule?t:{default:t}}function f(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39` &&
`;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}var c=[&quot;XX00000XXX&quot;,&quot;XX10000XXX&quot;,&quot;XX20000XXX&quot;,&quot;XXX00000XX&quot;,&quot;XXXX00000X&quot;,&quot;XXXXX00005&q` &&
`uot;,&quot;XXXXX00006&quot;,&quot;XXXXX00007&quot;,&quot;XXXXX00008&quot;,&quot;XXXXX00009&quot;],s=[[&quot;EEEOOO&quot;,&quot;OOOEEE&quot;],[&quot;EEOEOO&quot;,&quot;OOEOEE&quot;],[&quot;EEOOEO&quot;,&quot;OOEEOE&quot;],[&quot;EEOOOE&quot;,&quo` &&
`t;OOEEEO&quot;],[&quot;EOEEOO&quot;,&quot;OEOOEE&quot;],[&quot;EOOEEO&quot;,&quot;OEEOOE&quot;],[&quot;EOOOEE&quot;,&quot;OEEEOO&quot;],[&quot;EOEOEO&quot;,&quot;OEOEOE&quot;],[&quot;EOEOOE&quot;,&quot;OEOEEO&quot;],[&quot;EOOEOE&quot;,&quot;OEE` &&
`OEO&quot;]],l=function(t){function e(t,n){!function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e);var r=f(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,t,n));if(r.isValid=!1,-1!==t` &&
`.search(/^[0-9]{6}$/))r.middleDigits=t,r.upcA=p(t,&quot;0&quot;),r.text=n.text||&quot;&quot;+r.upcA[0]+t+r.upcA[r.upcA.length-1],r.isValid=!0;else{if(-1===t.search(/^[01][0-9]{7}$/))return f(r);if(r.middleDigits=t.substring(1,t.length-1),r.upcA=` &&
`p(r.middleDigits,t[0]),r.upcA[r.upcA.length-1]!==t[t.length-1])return f(r);r.isValid=!0}return r.displayValue=n.displayValue,n.fontSize&gt;10*n.width?r.fontSize=10*n.width:r.fontSize=n.fontSize,r.guardHeight=n.height+r.fontSize/2+n.textMargin,r}` &&
`return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,en` &&
`umerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),r(e,[{key:&quot;valid&quot;,value:function(){return this.isValid}},{key:&quot;encode&quot;,value:function(){return this.` &&
`options.flat?this.flatEncoding():this.guardedEncoding()}},{key:&quot;flatEncoding&quot;,value:function(){var t=&quot;&quot;;return t+=&quot;101&quot;,t+=this.encodeMiddleDigits(),{data:t+=&quot;010101&quot;,text:this.text}}},{key:&quot;guardedEn` &&
`coding&quot;,value:function(){var t=[];return this.displayValue&amp;&amp;t.push({data:&quot;00000000&quot;,text:this.text[0],options:{textAlign:&quot;left&quot;,fontSize:this.fontSize}}),t.push({data:&quot;101&quot;,options:{height:this.guardHei` &&
`ght}}),t.push({data:this.encodeMiddleDigits(),text:this.text.substring(1,7),options:{fontSize:this.fontSize}}),t.push({data:&quot;010101&quot;,options:{height:this.guardHeight}}),this.displayValue&amp;&amp;t.push({data:&quot;00000000&quot;,text:` &&
`this.text[7],options:{textAlign:&quot;right&quot;,fontSize:this.fontSize}}),t}},{key:&quot;encodeMiddleDigits&quot;,value:function(){var t=this.upcA[0],e=this.upcA[this.upcA.length-1],n=s[parseInt(e)][parseInt(t)];return(0,o.default)(this.middle` &&
`Digits,n)}}]),e}(i.default);function p(t,e){for(var n=parseInt(t[t.length-1]),r=c[n],o=&quot;&quot;,i=0,u=0;u&lt;r.length;u++){var f=r[u];o+=&quot;X&quot;===f?t[i++]:f}return&quot;&quot;+(o=&quot;&quot;+e+o)+(0,a.checksum)(o)}e.default=l},functi` &&
`on(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0}),e.ITF14=e.ITF=void 0;var r=i(n(10)),o=i(n(32));function i(t){return t&amp;&amp;t.__esModule?t:{default:t}}e.ITF=r.default,e.ITF14=o.default},function(t,e` &&
`,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});e.START_BIN=&quot;1010&quot;,e.END_BIN=&quot;11101&quot;,e.BINARIES=[&quot;00110&quot;,&quot;10001&quot;,&quot;01001&quot;,&quot;11000&quot;,&quot;00101&quot;,` &&
`&quot;10100&quot;,&quot;01100&quot;,&quot;00011&quot;,&quot;10010&quot;,&quot;01010&quot;]},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r,o=function(){function t(t,e){for(var n=0;n&lt;e.l` &&
`ength;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),i=n(10),a=(r` &&
`=i)&amp;&amp;r.__esModule?r:{default:r};var u=function(t){var e=t.substr(0,13).split(&quot;&quot;).map((function(t){return parseInt(t,10)})).reduce((function(t,e,n){return t+e*(3-n%2*2)}),0);return 10*Math.ceil(e/10)-e},f=function(t){function e(` &&
`t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),-1!==t.search(/^[0-9]{13}$/)&amp;&amp;(t+=u(t)),function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been in` &&
`itialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,t,n))}return function(t,e){if(&quot;function&quot;!=type` &&
`of e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&` &&
`amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),o(e,[{key:&quot;valid&quot;,value:function(){return-1!==this.data.search(/^[0-9]{14}$/)&amp;&amp;+this.data[13]===u(this.data)}}]),e}(a.default);e.default=f},function(t,e` &&
`,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0}),e.MSI1110=e.MSI1010=e.MSI11=e.MSI10=e.MSI=void 0;var r=f(n(4)),o=f(n(34)),i=f(n(35)),a=f(n(36)),u=f(n(37));function f(t){return t&amp;&amp;t.__esModule?t:{defa` &&
`ult:t}}e.MSI=r.default,e.MSI10=o.default,e.MSI11=i.default,e.MSI1010=a.default,e.MSI1110=u.default},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r,o=n(4),i=(r=o)&amp;&amp;r.__esModule?r:{d` &&
`efault:r},a=n(6);var u=function(t){function e(t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been init` &&
`ialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,t+(0,a.mod10)(t),n))}return function(t,e){if(&quot;functio` &&
`n&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:` &&
`!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),e}(i.default);e.default=u},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r,o=n(4),i=(r=o)&amp;&amp;r.` &&
`__esModule?r:{default:r},a=n(6);var u=function(t){function e(t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&` &&
`#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,t+(0,a.mod11)(t),n))}return function(t,e){i` &&
`f(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!` &&
`0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),e}(i.default);e.default=u},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r,o=n(4),i=(r` &&
`=o)&amp;&amp;r.__esModule?r:{default:r},a=n(6);var u=function(t){function e(t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),t+=(0,a.mod10)(t),t+=(0,a.mod10)(t),function(t` &&
`,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__proto__||Object.getPrototypeOf(e)).ca` &&
`ll(this,t,n))}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{construct` &&
`or:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),e}(i.default);e.default=u},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule` &&
`&quot;,{value:!0});var r,o=n(4),i=(r=o)&amp;&amp;r.__esModule?r:{default:r},a=n(6);var u=function(t){function e(t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),t+=(0,a.mo` &&
`d11)(t),t+=(0,a.mod10)(t),function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__p` &&
`roto__||Object.getPrototypeOf(e)).call(this,t,n))}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.crea` &&
`te(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),e}(i.default);e.default=u},function(t,e,n){&quot;use strict&quot;;Obje` &&
`ct.defineProperty(e,&quot;__esModule&quot;,{value:!0}),e.pharmacode=void 0;var r,o=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0` &&
`),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),i=n(0);var a=function(t){function e(t,n){!function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a` &&
` function&quot;)}(this,e);var r=function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,` &&
`(e.__proto__||Object.getPrototypeOf(e)).call(this,t,n));return r.number=parseInt(t,10),r}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super expression must either be null or a function, not &` &&
`quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),o(e,[{key:&quot;encode&quot;,va` &&
`lue:function(){for(var t=this.number,e=&quot;&quot;;!isNaN(t)&amp;&amp;0!=t;)t%2==0?(e=&quot;11100&quot;+e,t=(t-2)/2):(e=&quot;100&quot;+e,t=(t-1)/2);return{data:e=e.slice(0,-2),text:this.text}}},{key:&quot;valid&quot;,value:function(){return th` &&
`is.number&gt;=3&amp;&amp;this.number&lt;=131070}}]),e}(((r=i)&amp;&amp;r.__esModule?r:{default:r}).default);e.pharmacode=a},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0}),e.codabar=void 0;var r,` &&
`o=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.` &&
`prototype,n),r&amp;&amp;t(e,r),e}}(),i=n(0);var a=function(t){function e(t,n){!function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),0===t.search(/^[0-9\-\$\:\.\+\/]+$/)&amp;&amp;(t=&quot;` &&
`A&quot;+t+&quot;A&quot;);var r=function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(` &&
`e.__proto__||Object.getPrototypeOf(e)).call(this,t.toUpperCase(),n));return r.text=r.options.text||r.text.replace(/[A-D]/g,&quot;&quot;),r}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)throw new TypeError(&quot;Super e` &&
`xpression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf?Object.setPrototypeOf(t,e):t.` &&
`__proto__=e)}(e,t),o(e,[{key:&quot;valid&quot;,value:function(){return-1!==this.data.search(/^[A-D][0-9\-\$\:\.\+\/]+[A-D]$/)}},{key:&quot;encode&quot;,value:function(){for(var t=[],e=this.getEncodings(),n=0;n&lt;this.data.length;n++)t.push(e[th` &&
`is.data.charAt(n)]),n!==this.data.length-1&amp;&amp;t.push(&quot;0&quot;);return{text:this.text,data:t.join(&quot;&quot;)}}},{key:&quot;getEncodings&quot;,value:function(){return{0:&quot;101010011&quot;,1:&quot;101011001&quot;,2:&quot;101001011&` &&
`quot;,3:&quot;110010101&quot;,4:&quot;101101001&quot;,5:&quot;110101001&quot;,6:&quot;100101011&quot;,7:&quot;100101101&quot;,8:&quot;100110101&quot;,9:&quot;110100101&quot;,&quot;-&quot;:&quot;101001101&quot;,$:&quot;101100101&quot;,&quot;:&quo` &&
`t;:&quot;1101011011&quot;,&quot;/&quot;:&quot;1101101011&quot;,&quot;.&quot;:&quot;1101101101&quot;,&quot;+&quot;:&quot;1011011011&quot;,A:&quot;1011001001&quot;,B:&quot;1001001011&quot;,C:&quot;1010010011&quot;,D:&quot;1010011001&quot;}}}]),e}(` &&
`((r=i)&amp;&amp;r.__esModule?r:{default:r}).default);e.codabar=a},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0}),e.GenericBarcode=void 0;var r,o=function(){function t(t,e){for(var n=0;n&lt;e.len` &&
`gth;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),i=n(0);var a=f` &&
`unction(t){function e(t,n){return function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,e),function(t,e){if(!t)throw new ReferenceError(&quot;this hasn&#39;t been initialised - super() hasn&#` &&
`39;t been called&quot;);return!e||&quot;object&quot;!=typeof e&amp;&amp;&quot;function&quot;!=typeof e?t:e}(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,t,n))}return function(t,e){if(&quot;function&quot;!=typeof e&amp;&amp;null!==e)thr` &&
`ow new TypeError(&quot;Super expression must either be null or a function, not &quot;+typeof e);t.prototype=Object.create(e&amp;&amp;e.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}),e&amp;&amp;(Object.setPrototypeOf` &&
`?Object.setPrototypeOf(t,e):t.__proto__=e)}(e,t),o(e,[{key:&quot;encode&quot;,value:function(){return{data:&quot;10101010101010101010101010101010101010101&quot;,text:this.text}}},{key:&quot;valid&quot;,value:function(){return!0}}]),e}(((r=i)&amp` &&
`;&amp;r.__esModule?r:{default:r}).default);e.GenericBarcode=a},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0}),e.default=function(t){var e=[];return function t(n){if(Array.isArray(n))for(var r=0;` &&
`r&lt;n.length;r++)t(n[r]);else n.text=n.text||&quot;&quot;,n.data=n.data||&quot;&quot;,e.push(n)}(t),e}},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0}),e.default=function(t){return t.marginTop=t` &&
`.marginTop||t.margin,t.marginBottom=t.marginBottom||t.margin,t.marginRight=t.marginRight||t.margin,t.marginLeft=t.marginLeft||t.margin,t}},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r=&q` &&
`uot;function&quot;==typeof Symbol&amp;&amp;&quot;symbol&quot;==typeof Symbol.iterator?function(t){return typeof t}:function(t){return t&amp;&amp;&quot;function&quot;==typeof Symbol&amp;&amp;t.constructor===Symbol&amp;&amp;t!==Symbol.prototype?&q` &&
`uot;symbol&quot;:typeof t},o=u(n(44)),i=u(n(45)),a=n(14);function u(t){return t&amp;&amp;t.__esModule?t:{default:t}}function f(t){if(&quot;string&quot;==typeof t)return function(t){var e=document.querySelectorAll(t);if(0===e.length)return;for(va` &&
`r n=[],r=0;r&lt;e.length;r++)n.push(f(e[r]));return n}(t);if(Array.isArray(t)){for(var e=[],n=0;n&lt;t.length;n++)e.push(f(t[n]));return e}if(&quot;undefined&quot;!=typeof HTMLCanvasElement&amp;&amp;t instanceof HTMLImageElement)return u=t,{elem` &&
`ent:c=document.createElement(&quot;canvas&quot;),options:(0,o.default)(u),renderer:i.default.CanvasRenderer,afterRender:function(){u.setAttribute(&quot;src&quot;,c.toDataURL())}};if(t&amp;&amp;t.nodeName&amp;&amp;&quot;svg&quot;===t.nodeName.toL` &&
`owerCase()||&quot;undefined&quot;!=typeof SVGElement&amp;&amp;t instanceof SVGElement)return{element:t,options:(0,o.default)(t),renderer:i.default.SVGRenderer};if(&quot;undefined&quot;!=typeof HTMLCanvasElement&amp;&amp;t instanceof HTMLCanvasEl` &&
`ement)return{element:t,options:(0,o.default)(t),renderer:i.default.CanvasRenderer};if(t&amp;&amp;t.getContext)return{element:t,renderer:i.default.CanvasRenderer};if(t&amp;&amp;&quot;object&quot;===(void 0===t?&quot;undefined&quot;:r(t))&amp;&amp` &&
`;!t.nodeName)return{element:t,renderer:i.default.ObjectRenderer};throw new a.InvalidElementException;var u,c}e.default=f},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r=i(n(11)),o=i(n(12))` &&
`;function i(t){return t&amp;&amp;t.__esModule?t:{default:t}}e.default=function(t){var e={};for(var n in o.default)o.default.hasOwnProperty(n)&amp;&amp;(t.hasAttribute(&quot;jsbarcode-&quot;+n.toLowerCase())&amp;&amp;(e[n]=t.getAttribute(&quot;js` &&
`barcode-&quot;+n.toLowerCase())),t.hasAttribute(&quot;data-&quot;+n.toLowerCase())&amp;&amp;(e[n]=t.getAttribute(&quot;data-&quot;+n.toLowerCase())));return e.value=t.getAttribute(&quot;jsbarcode-value&quot;)||t.getAttribute(&quot;data-value&quo` &&
`t;),e=(0,r.default)(e)}},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r=a(n(46)),o=a(n(47)),i=a(n(48));function a(t){return t&amp;&amp;t.__esModule?t:{default:t}}e.default={CanvasRenderer:` &&
`r.default,SVGRenderer:o.default,ObjectRenderer:i.default}},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r,o=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerabl` &&
`e=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),i=n(7),a=(r=i)&amp;&amp;r.__esModule?r:{defau` &&
`lt:r},u=n(13);var f=function(){function t(e,n,r){!function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,t),this.canvas=e,this.encodings=n,this.options=r}return o(t,[{key:&quot;render&quot;,va` &&
`lue:function(){if(!this.canvas.getContext)throw new Error(&quot;The browser does not support canvas.&quot;);this.prepareCanvas();for(var t=0;t&lt;this.encodings.length;t++){var e=(0,a.default)(this.options,this.encodings[t].options);this.drawCan` &&
`vasBarcode(e,this.encodings[t]),this.drawCanvasText(e,this.encodings[t]),this.moveCanvasDrawing(this.encodings[t])}this.restoreCanvas()}},{key:&quot;prepareCanvas&quot;,value:function(){var t=this.canvas.getContext(&quot;2d&quot;);t.save(),(0,u.` &&
`calculateEncodingAttributes)(this.encodings,this.options,t);var e=(0,u.getTotalWidthOfEncodings)(this.encodings),n=(0,u.getMaximumHeightOfEncodings)(this.encodings);this.canvas.width=e+this.options.marginLeft+this.options.marginRight,this.canvas` &&
`.height=n,t.clearRect(0,0,this.canvas.width,this.canvas.height),this.options.background&amp;&amp;(t.fillStyle=this.options.background,t.fillRect(0,0,this.canvas.width,this.canvas.height)),t.translate(this.options.marginLeft,0)}},{key:&quot;drawC` &&
`anvasBarcode&quot;,value:function(t,e){var n,r=this.canvas.getContext(&quot;2d&quot;),o=e.data;n=&quot;top&quot;==t.textPosition?t.marginTop+t.fontSize+t.textMargin:t.marginTop,r.fillStyle=t.lineColor;for(var i=0;i&lt;o.length;i++){var a=i*t.wid` &&
`th+e.barcodePadding;&quot;1&quot;===o[i]?r.fillRect(a,n,t.width,t.height):o[i]&amp;&amp;r.fillRect(a,n,t.width,t.height*o[i])}}},{key:&quot;drawCanvasText&quot;,value:function(t,e){var n,r,o=this.canvas.getContext(&quot;2d&quot;),i=t.fontOptions` &&
`+&quot; &quot;+t.fontSize+&quot;px &quot;+t.font;t.displayValue&amp;&amp;(r=&quot;top&quot;==t.textPosition?t.marginTop+t.fontSize-t.textMargin:t.height+t.textMargin+t.marginTop+t.fontSize,o.font=i,&quot;left&quot;==t.textAlign||e.barcodePadding` &&
`&gt;0?(n=0,o.textAlign=&quot;left&quot;):&quot;right&quot;==t.textAlign?(n=e.width-1,o.textAlign=&quot;right&quot;):(n=e.width/2,o.textAlign=&quot;center&quot;),o.fillText(e.text,n,r))}},{key:&quot;moveCanvasDrawing&quot;,value:function(t){this.` &&
`canvas.getContext(&quot;2d&quot;).translate(t.width,0)}},{key:&quot;restoreCanvas&quot;,value:function(){this.canvas.getContext(&quot;2d&quot;).restore()}}]),t}();e.default=f},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;` &&
`__esModule&quot;,{value:!0});var r,o=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return fun` &&
`ction(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}(),i=n(7),a=(r=i)&amp;&amp;r.__esModule?r:{default:r},u=n(13);var f=&quot;http://www.w3.org/2000/svg&quot;,c=function(){function t(e,n,r){!function(t,e){if(!(t instanceof e))th` &&
`row new TypeError(&quot;Cannot call a class as a function&quot;)}(this,t),this.svg=e,this.encodings=n,this.options=r,this.document=r.xmlDocument||document}return o(t,[{key:&quot;render&quot;,value:function(){var t=this.options.marginLeft;this.pr` &&
`epareSVG();for(var e=0;e&lt;this.encodings.length;e++){var n=this.encodings[e],r=(0,a.default)(this.options,n.options),o=this.createGroup(t,r.marginTop,this.svg);this.setGroupOptions(o,r),this.drawSvgBarcode(o,r,n),this.drawSVGText(o,r,n),t+=n.w` &&
`idth}}},{key:&quot;prepareSVG&quot;,value:function(){for(;this.svg.firstChild;)this.svg.removeChild(this.svg.firstChild);(0,u.calculateEncodingAttributes)(this.encodings,this.options);var t=(0,u.getTotalWidthOfEncodings)(this.encodings),e=(0,u.g` &&
`etMaximumHeightOfEncodings)(this.encodings),n=t+this.options.marginLeft+this.options.marginRight;this.setSvgAttributes(n,e),this.options.background&amp;&amp;this.drawRect(0,0,n,e,this.svg).setAttribute(&quot;style&quot;,&quot;fill:&quot;+this.op` &&
`tions.background+&quot;;&quot;)}},{key:&quot;drawSvgBarcode&quot;,value:function(t,e,n){var r,o=n.data;r=&quot;top&quot;==e.textPosition?e.fontSize+e.textMargin:0;for(var i=0,a=0,u=0;u&lt;o.length;u++)a=u*e.width+n.barcodePadding,&quot;1&quot;==` &&
`=o[u]?i++:i&gt;0&amp;&amp;(this.drawRect(a-e.width*i,r,e.width*i,e.height,t),i=0);i&gt;0&amp;&amp;this.drawRect(a-e.width*(i-1),r,e.width*i,e.height,t)}},{key:&quot;drawSVGText&quot;,value:function(t,e,n){var r,o,i=this.document.createElementNS(` &&
`f,&quot;text&quot;);e.displayValue&amp;&amp;(i.setAttribute(&quot;style&quot;,&quot;font:&quot;+e.fontOptions+&quot; &quot;+e.fontSize+&quot;px &quot;+e.font),o=&quot;top&quot;==e.textPosition?e.fontSize-e.textMargin:e.height+e.textMargin+e.font` &&
`Size,&quot;left&quot;==e.textAlign||n.barcodePadding&gt;0?(r=0,i.setAttribute(&quot;text-anchor&quot;,&quot;start&quot;)):&quot;right&quot;==e.textAlign?(r=n.width-1,i.setAttribute(&quot;text-anchor&quot;,&quot;end&quot;)):(r=n.width/2,i.setAttr` &&
`ibute(&quot;text-anchor&quot;,&quot;middle&quot;)),i.setAttribute(&quot;x&quot;,r),i.setAttribute(&quot;y&quot;,o),i.appendChild(this.document.createTextNode(n.text)),t.appendChild(i))}},{key:&quot;setSvgAttributes&quot;,value:function(t,e){var ` &&
`n=this.svg;n.setAttribute(&quot;width&quot;,t+&quot;px&quot;),n.setAttribute(&quot;height&quot;,e+&quot;px&quot;),n.setAttribute(&quot;x&quot;,&quot;0px&quot;),n.setAttribute(&quot;y&quot;,&quot;0px&quot;),n.setAttribute(&quot;viewBox&quot;,&quo` &&
`t;0 0 &quot;+t+&quot; &quot;+e),n.setAttribute(&quot;xmlns&quot;,f),n.setAttribute(&quot;version&quot;,&quot;1.1&quot;),n.setAttribute(&quot;style&quot;,&quot;transform: translate(0,0)&quot;)}},{key:&quot;createGroup&quot;,value:function(t,e,n){` &&
`var r=this.document.createElementNS(f,&quot;g&quot;);return r.setAttribute(&quot;transform&quot;,&quot;translate(&quot;+t+&quot;, &quot;+e+&quot;)&quot;),n.appendChild(r),r}},{key:&quot;setGroupOptions&quot;,value:function(t,e){t.setAttribute(&q` &&
`uot;style&quot;,&quot;fill:&quot;+e.lineColor+&quot;;&quot;)}},{key:&quot;drawRect&quot;,value:function(t,e,n,r,o){var i=this.document.createElementNS(f,&quot;rect&quot;);return i.setAttribute(&quot;x&quot;,t),i.setAttribute(&quot;y&quot;,e),i.s` &&
`etAttribute(&quot;width&quot;,n),i.setAttribute(&quot;height&quot;,r),o.appendChild(i),i}}]),t}();e.default=c},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r=function(){function t(t,e){for` &&
`(var n=0;n&lt;e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e` &&
`}}();var o=function(){function t(e,n,r){!function(t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,t),this.object=e,this.encodings=n,this.options=r}return r(t,[{key:&quot;render&quot;,value:funct` &&
`ion(){this.object.encodings=this.encodings}}]),t}();e.default=o},function(t,e,n){&quot;use strict&quot;;Object.defineProperty(e,&quot;__esModule&quot;,{value:!0});var r=function(){function t(t,e){for(var n=0;n&lt;e.length;n++){var r=e[n];r.enume` &&
`rable=r.enumerable||!1,r.configurable=!0,&quot;value&quot;in r&amp;&amp;(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&amp;&amp;t(e.prototype,n),r&amp;&amp;t(e,r),e}}();var o=function(){function t(e){!function(` &&
`t,e){if(!(t instanceof e))throw new TypeError(&quot;Cannot call a class as a function&quot;)}(this,t),this.api=e}return r(t,[{key:&quot;handleCatch&quot;,value:function(t){if(&quot;InvalidInputException&quot;!==t.name)throw t;if(this.api._option` &&
`s.valid===this.api._defaults.valid)throw t.message;this.api._options.valid(!1),this.api.render=function(){}}},{key:&quot;wrapBarcodeCall&quot;,value:function(t){try{var e=t.apply(void 0,arguments);return this.api._options.valid(!0),e}catch(t){re` &&
`turn this.handleCatch(t),this.api}}}]),t}();e.default=o}]);`.

  ENDMETHOD.

ENDCLASS.
