name: ABAP_702

on:
  pull_request:

permissions:
  contents: read

jobs:
  ABAP_702:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v5
      with:
        ref: 702
    - uses: actions/setup-node@v5
      with:
        node-version: 20
    - run: npm ci
    - run: rm -rf src/00
    - run: npm run downport
    - run: npx abaplint .github/abaplint/abap_702.jsonc
