name: abap-cloud

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: abap-cloud-${{ github.ref }}
  cancel-in-progress: true

jobs:
  abap-cloud:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v6
      with:
        node-version: '22'
        cache: 'npm'
    - run: npm ci
    - run: rm -r src/01
    - run: npx abaplint .github/abaplint/abap_cloud.jsonc
