name: launchpad

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  launchpad:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 20

    - run: npm ci
    - run: npm run launchpad

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        add-paths: src
        commit-message: Regenerate launchpad
        author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
        committer: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
        branch: launchpad/regenerate
        delete-branch: true
        title: Regenerate launchpad
        body: Automated launchpad regeneration.
